# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.CharField(max_length=255),
        ),
    ]
