# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0003_auto_20170111_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=1),
        ),
    ]
