# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0004_auto_20170120_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried'), ('divorce', 'divorce'), ('widow', 'widow'), ('widower', 'widower')], max_length=1),
        ),
    ]
