# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0008_auto_20170120_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='address_id',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=16),
        ),
    ]
