# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0009_auto_20170120_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(default=None),
        ),
    ]
