# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0010_auto_20170120_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
