# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0011_auto_20170121_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=96)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('username', models.CharField(max_length=96)),
                ('status', models.CharField(max_length=216)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=96)),
                ('role', models.CharField(max_length=96)),
                ('status', models.CharField(max_length=96)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='login',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycommunity.user'),
        ),
    ]
