# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 06:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0012_auto_20170207_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
