# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0013_auto_20170314_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.TextField(),
        ),
    ]
