# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0014_auto_20170320_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Send_last_notification_before',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(max_length=216),
        ),
        migrations.AlterField(
            model_name='events',
            name='is_open_event',
            field=models.CharField(max_length=216),
        ),
    ]
