# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0015_auto_20170324_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='events',
            name='longitude',
        ),
    ]
