# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0016_auto_20170324_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Send_last_notification_before',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_photo',
        ),
        migrations.RemoveField(
            model_name='events',
            name='is_open_event',
        ),
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
    ]
