# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0017_auto_20170327_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='inviteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviteesId', to='mycommunity.Member')),
                ('inviterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviterId', to='mycommunity.Member')),
            ],
            options={
                'db_table': 'inviteList',
            },
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
