# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0019_auto_20170327_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelist',
            name='event',
        ),
        migrations.RemoveField(
            model_name='invitelist',
            name='inviteesId',
        ),
        migrations.DeleteModel(
            name='inviteList',
        ),
    ]
