# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0020_auto_20170327_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='inviteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycommunity.events')),
                ('inviteesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycommunity.Member')),
            ],
            options={
                'db_table': 'inviteList',
            },
        ),
    ]
