# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0027_auto_20170404_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='event_registery',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycommunity.Events'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycommunity.Events'),
        ),
        migrations.AlterField(
            model_name='events',
            name='Allergies',
            field=models.BooleanField(verbose_name='Allergies:'),
        ),
        migrations.AlterField(
            model_name='invitelist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycommunity.Events'),
        ),
    ]
