# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycommunity', '0029_auto_20170415_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnotification',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='group_member',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='group_member',
            name='mem_id',
        ),
        migrations.RemoveField(
            model_name='invitelist',
            name='event',
        ),
        migrations.RemoveField(
            model_name='invitelist',
            name='inviteesId',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Allergies',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AlterField(
            model_name='event_registery',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycommunity.Events'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('other', 'other')], default='Female', max_length=16),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Widower', 'Widower')], default='Unmarried', max_length=16),
        ),
        migrations.DeleteModel(
            name='eventnotification',
        ),
        migrations.DeleteModel(
            name='group',
        ),
        migrations.DeleteModel(
            name='group_member',
        ),
        migrations.DeleteModel(
            name='inviteList',
        ),
    ]
